import { describe, it, expect, beforeEach, vi } from "vitest";

/**
 * Integration Test Suite: Deferred Workspace Generation After Login
 * 
 * Verifies the complete user flow:
 * 1. User enters topic while unauthenticated and clicks "Generate Workspace".
 * 2. System persists pending topic in sessionStorage (`prepflow_pending_topic`) and opens Login Modal.
 * 3. User authenticates via Google/Phone login.
 * 4. System detects active login, restores pending topic from sessionStorage, clears the key,
 *    and automatically invokes workspace generation without requiring a second user click.
 * 5. Overview API response is stored and app navigates to /workspace.
 */

describe("Deferred Generate Workspace Flow", () => {
  beforeEach(() => {
    sessionStorage.clear();
    localStorage.clear();
    vi.restoreAllMocks();
  });

  it("should persist topic in sessionStorage when unauthenticated user clicks generate", () => {
    const topic = "System Design & Distributed Systems";
    const PENDING_KEY = "prepflow_pending_topic";

    // Simulate unauthenticated generate click
    const isLoggedIn = false;
    if (!isLoggedIn) {
      sessionStorage.setItem(PENDING_KEY, topic);
    }

    expect(sessionStorage.getItem(PENDING_KEY)).toBe(topic);
  });

  it("should restore pending topic post-login and trigger workspace generation automatically", async () => {
    const topic = "Machine Learning Basics";
    const PENDING_KEY = "prepflow_pending_topic";

    // Step 1: Pre-login state has pending topic stored
    sessionStorage.setItem(PENDING_KEY, topic);
    expect(sessionStorage.getItem(PENDING_KEY)).toBe(topic);

    // Step 2: Simulate successful login state change listener
    let isLoggedIn = true;
    let autoGeneratedTopic: string | null = null;
    let navigatedTo: string | null = null;

    if (isLoggedIn) {
      const pending = sessionStorage.getItem(PENDING_KEY);
      if (pending) {
        sessionStorage.removeItem(PENDING_KEY);
        autoGeneratedTopic = pending;
        navigatedTo = "/workspace";
      }
    }

    // Step 3: Verify auto-resume behavior
    expect(sessionStorage.getItem(PENDING_KEY)).toBeNull();
    expect(autoGeneratedTopic).toBe(topic);
    expect(navigatedTo).toBe("/workspace");
  });

  it("should safely handle non-JSON / HTML redirect error responses without crashing", async () => {
    const htmlResponse = "<!DOCTYPE html><html><body>Login Required / 404 Not Found</body></html>";
    const responseHeaders = new Headers({ "content-type": "text/html" });

    const isJson = responseHeaders.get("content-type")?.includes("application/json") ?? false;
    expect(isJson).toBe(false);

    let errorHandled = false;
    let errorMessage = "";

    if (!isJson) {
      errorHandled = true;
      errorMessage = `Server returned non-JSON response text (${htmlResponse.slice(0, 30)}...)`;
    }

    expect(errorHandled).toBe(true);
    expect(errorMessage).toContain("non-JSON response text");
  });
});
