import React, { useState } from "react";
import { useLocation } from "wouter";
import { Layout } from "@/components/layout";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { useWorkspaceStore } from "@/lib/workspace-store";
import { useAuth } from "@/lib/auth-context";
import { requestQueue } from "@/lib/request-queue";
import { prefetchWorkspaceModules } from "@/hooks/use-module-loader";
import {
  Brain,
  Sparkles,
  ArrowRight,
  History,
  Clock,
  BookOpen,
  Zap,
  Loader2,
  AlertTriangle,
} from "lucide-react";
import { motion } from "framer-motion";

const EXAMPLE_TOPICS = [
  "React Hooks",
  "Machine Learning Basics",
  "Operating Systems",
  "System Design",
  "Java Collections",
  "PostgreSQL Indexing",
];

export const PENDING_TOPIC_STORAGE_KEY = "prepflow_pending_topic";

export function LandingPage() {
  const [, setLocation] = useLocation();
  const [topic, setTopic] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const { sessions, saveSession, setCurrentSession } = useWorkspaceStore();
  const { isLoggedIn, openLoginModal } = useAuth();

  const pendingTopicRef = React.useRef<string | null>(null);

  const handleGenerate = React.useCallback(async (selectedTopic?: string) => {
    const topicToUse = selectedTopic || topic;
    const trimmed = topicToUse.trim();
    if (!trimmed || loading) return;

    if (!isLoggedIn) {
      sessionStorage.setItem(PENDING_TOPIC_STORAGE_KEY, trimmed);
      pendingTopicRef.current = trimmed;
      setError("Please sign in or sign up to generate a workspace.");
      openLoginModal();
      return;
    }

    setTopic(trimmed);
    setLoading(true);
    setError(null);

    try {
      // 1. Fetch overview only (fast ~1-2s response)
      const overviewData = await requestQueue.fetchModule(
        trimmed,
        "overview",
        "/api/overview"
      );

      // 2. Save session with overview data
      saveSession(trimmed, overviewData as any);

      // 3. Trigger background prefetch for remaining modules
      prefetchWorkspaceModules(trimmed);

      // 4. Navigate immediately to workspace
      setLocation("/workspace");
    } catch (err: any) {
      setError(err?.message ?? "Failed to generate workspace. Please try again.");
    } finally {
      setLoading(false);
    }
  }, [topic, loading, isLoggedIn, openLoginModal, saveSession, setLocation]);

  // Auto-generate topic seamlessly after successful login
  React.useEffect(() => {
    if (isLoggedIn) {
      const storedPending = sessionStorage.getItem(PENDING_TOPIC_STORAGE_KEY) || pendingTopicRef.current;
      if (storedPending) {
        sessionStorage.removeItem(PENDING_TOPIC_STORAGE_KEY);
        pendingTopicRef.current = null;
        setError(null);
        setTopic(storedPending);
        handleGenerate(storedPending);
      }
    }
  }, [isLoggedIn, handleGenerate]);

  const handleResumeSession = (id: string) => {
    setCurrentSession(id);
    setLocation("/workspace");
  };

  const sessionsList = Object.values(sessions).sort((a: any, b: any) => b.createdAt - a.createdAt);

  return (
    <Layout>
      <div className="flex-1 flex flex-col items-center justify-center px-4 py-12 md:py-24 max-w-4xl mx-auto w-full relative">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-primary/20 blur-[130px] rounded-full pointer-events-none -z-10 animate-pulse" />

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center space-y-6 mb-10"
        >
          <Badge variant="outline" className="px-4 py-1.5 rounded-full border-primary/30 bg-primary/5 text-primary text-sm shadow-sm backdrop-blur-sm">
            <Sparkles className="w-4 h-4 mr-2" /> AI-Powered Interactive Study Workspace
          </Badge>
          <h1 className="text-5xl md:text-7xl font-bold font-display tracking-tight text-foreground leading-[1.1]">
            Master any topic <br className="hidden md:block" />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary via-indigo-400 to-purple-500">
              in minutes, not hours.
            </span>
          </h1>
          <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto leading-relaxed">
            Instant flashcards, 10+ quiz questions, interview prep, cheat sheets, and multi-language code breakdowns generated by AI.
          </p>
        </motion.div>

        {/* Input Box */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 0.1 }}
          className="w-full max-w-2xl mb-8"
        >
          <Card className="border-border/60 shadow-2xl bg-card/80 backdrop-blur-xl rounded-2xl overflow-hidden p-2">
            <CardContent className="p-2 space-y-4">
              <Textarea
                placeholder="What topic do you want to learn today? (e.g. Binary Search Trees, React Server Components...)"
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && !e.shiftKey) {
                    e.preventDefault();
                    handleGenerate();
                  }
                }}
                disabled={loading}
                className="border-none focus-visible:ring-0 text-base md:text-lg resize-none min-h-[100px] p-4 bg-transparent"
              />

              {error && (
                <div className="p-3 bg-red-500/10 border border-red-500/20 rounded-xl text-xs text-red-500 flex items-center gap-2">
                  <AlertTriangle className="w-4 h-4 shrink-0" />
                  {error}
                </div>
              )}

              <div className="flex flex-col sm:flex-row items-center justify-between gap-3 pt-2 border-t border-border/40 px-2 pb-1">
                <span className="text-xs text-muted-foreground flex items-center gap-1.5">
                  <Zap className="w-3.5 h-3.5 text-amber-500" /> Modular AI architecture — instant overview response
                </span>
                <Button
                  onClick={() => handleGenerate()}
                  disabled={!topic.trim() || loading}
                  size="lg"
                  className="w-full sm:w-auto rounded-xl px-6 font-semibold shadow-lg shadow-primary/25 gap-2"
                >
                  {loading ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin" /> Generating Workspace...
                    </>
                  ) : (
                    <>
                      Generate Workspace <ArrowRight className="w-4 h-4" />
                    </>
                  )}
                </Button>
              </div>
            </CardContent>
          </Card>

          {/* Example Pills */}
          <div className="flex flex-wrap items-center justify-center gap-2 mt-4">
            <span className="text-xs text-muted-foreground font-medium mr-1">Try:</span>
            {EXAMPLE_TOPICS.map((t) => (
              <button
                key={t}
                onClick={() => handleGenerate(t)}
                disabled={loading}
                className="text-xs px-3 py-1.5 rounded-full bg-secondary/80 hover:bg-secondary text-secondary-foreground transition-all hover:scale-105 border border-border/40 disabled:opacity-50"
              >
                {t}
              </button>
            ))}
          </div>
        </motion.div>

        {/* Recent Workspaces */}
        {sessionsList.length > 0 && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="w-full max-w-3xl mt-8 space-y-4"
          >
            <div className="flex items-center justify-between px-1">
              <h2 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground flex items-center gap-2">
                <History className="w-4 h-4 text-primary" /> Your Saved Workspaces
              </h2>
              <span className="text-xs font-mono text-muted-foreground">{sessionsList.length} saved</span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {sessionsList.map((s: any) => (
                <Card
                  key={s.id}
                  onClick={() => handleResumeSession(s.id)}
                  className="border-border/60 hover:border-primary/50 transition-all cursor-pointer hover:shadow-md group bg-card/50"
                >
                  <CardContent className="p-4 flex items-center justify-between">
                    <div className="space-y-1 min-w-0 pr-3">
                      <h3 className="font-semibold text-sm truncate group-hover:text-primary transition-colors flex items-center gap-2">
                        <BookOpen className="w-4 h-4 text-primary shrink-0" />
                        {s.topic}
                      </h3>
                      <div className="flex items-center gap-2 text-xs text-muted-foreground">
                        <Clock className="w-3 h-3" />
                        {new Date(s.createdAt).toLocaleDateString(undefined, { month: "short", day: "numeric" })}
                        <Badge variant="secondary" className="text-[10px] px-1.5 py-0 h-4 font-normal">
                          {s.workspace.difficulty || "Intermediate"}
                        </Badge>
                      </div>
                    </div>
                    <ArrowRight className="w-4 h-4 text-muted-foreground group-hover:text-primary group-hover:translate-x-1 transition-all shrink-0" />
                  </CardContent>
                </Card>
              ))}
            </div>
          </motion.div>
        )}
      </div>
    </Layout>
  );
}
